[tools]
# Shell
usage = "latest"
starship = "latest"
sheldon = "latest"
fzf = "latest"
bat = "latest"
eza = "latest"
# Git
ghq = "latest"
github-cli = "latest"
# Development
node = "latest"
ni = "latest"
