#:schema https://mise.en.dev/schema/mise.json

[settings]
dotfiles.root = "~/src/github.com/mouse484/dotfiles"

[dotfiles]
"~/.config/" = { source = "~/src/github.com/mouse484/dotfiles/.config/", mode = "symlink-each" }
