#:schema https://mise.en.dev/schema/mise.json

[settings]
dotfiles.root = "~/src/dotfiles"

# Bootstrap configuration for mise: https://mise.jdx.dev/bootstrap.html#how-it-runs

# === 1. Packages ===
[bootstrap.packages]
# zsh
"apt:zsh" = "latest"
# git
"apt:git" = "latest"
"brew:git" = "latest"
"brew-cask:git-credential-manager" = "latest"

[bootstrap.hooks.post-packages]
run = '''
if [ -f /etc/zsh/zshenv ]; then
  TARGET="/etc/zsh/zshenv"
elif [ -f /etc/zshenv ]; then
  TARGET="/etc/zshenv"
fi

if [ -n "$TARGET" ]; then
  if ! grep -q "export ZDOTDIR" "$TARGET"; then
    echo 'export ZDOTDIR="$HOME/.config/zsh"' | sudo tee -a "$TARGET"
  fi
fi
'''

# === 3. Dotfiles ===
[dotfiles]
"~/.config/" = { source = "~/src/dotfiles/.config/", mode = "symlink-each" }

# === 8. User Configuration ===
[bootstrap.user]
login_shell = "/bin/zsh"

# === 9. Tools ===
[tools]
starship = "latest"
